# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TyXjUQ9Mn2d49SXkZVv0zFZXTCb2-axx
"""



"""*markdown*
**markdown**
   

1.   List item
2.   List item


*   List item
*   List item
"""

12+45

57

34<45

x=int(input("enter the value of x"))#variable creation
y=int(input("enter the value of y"))#variable
print(x+y) #+,-,*,/,%,//,**
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x//y)
print(2**5)

x=10 #integer
y=23,56#loat
z=5+6j #compiex
a=4+3j
print(type(x),type(y),type(z))
print(z+a,z-a,z*a)

type(23>45)

name="preethi"
print(type(name))

name=input("enter your name")
print("hello,",name)

"""create two variables and accept value from the user ->name and age o/p:hello i am.........and my age......"""